const { runShell } = require('../utils/shell');
const { confirm } = require('@inquirer/prompts');
const fs = require('fs');
const path = require('path');

function generateVapidKeys(appPath) {
    try {
        const output = runShell(`cd "${appPath}" && npx web-push generate-vapid-keys --json`);
        return JSON.parse(output);
    } catch {
        const webpush = require('web-push');
        return webpush.generateVAPIDKeys();
    }
}

function generateAuthSecret() {
    try {
        return runShell('openssl rand -base64 32');
    } catch {
        return require('crypto').randomBytes(32).toString('base64');
    }
}

/**
 * Generates the .env file from wizard answers.
 * Creates the app directory if it doesn't exist.
 */
async function generateEnv(answers, spinner) {
    const { appPath, domain, adminEmail, port, mode } = answers;

    // Ensure the directory exists
    if (!fs.existsSync(appPath)) {
        fs.mkdirSync(appPath, { recursive: true });
    }

    // Ask before overwriting an existing .env
    const envPath = path.join(appPath, '.env');
    if (fs.existsSync(envPath)) {
        spinner.stop();
        const overwrite = await confirm({
            message: '.env already exists — overwrite it?',
            default: false,
        });
        if (!overwrite) {
            return envPath; // keep existing .env, skip generation
        }
        spinner.start();
    }

    spinner.text = 'Generating AUTH_SECRET…';
    const authSecret = generateAuthSecret();
    const deploySecret = generateAuthSecret();

    let vapidPublic = '';
    let vapidPrivate = '';
    if (answers.generateVapid) {
        spinner.text = 'Generating VAPID keys…';
        try {
            const keys = generateVapidKeys(appPath);
            vapidPublic = keys.publicKey;
            vapidPrivate = keys.privateKey;
        } catch {
            spinner.warn('Could not generate VAPID keys — fill in manually later.');
        }
    }

    const dbPath = path.join(appPath, 'dev.db'); // prisma.config.ts uses file:./dev.db (project root)
    const appUrl = mode === 'local' ? `http://localhost:${port}` : `https://${domain}`;

    const lines = [
        '# Generated by Beer Pong Setup Wizard',
        `# Date: ${new Date().toISOString()}`,
        '',
        '# Database',
        `DATABASE_URL="file:${dbPath}"`,
        '',
        '# Auth',
        `AUTH_URL="${appUrl}"`,
        `AUTH_SECRET="${authSecret}"`,
        `ADMIN_EMAIL="${adminEmail}"`,
        '',
        '# App',
        `APP_URL="${appUrl}"`,
        `NEXT_PUBLIC_APP_URL="${appUrl}"`,
        `NEXT_PUBLIC_APP_NAME="${answers.appName}"`,
        `PORT=${port}`,
        `NEXT_PUBLIC_LOCALE="${answers.locale || 'en'}"`,
        '',
        '# WebAuthn (Passkeys)',
        `WEBAUTHN_RP_ID="${mode === 'local' ? 'localhost' : domain}"`,
        `WEBAUTHN_ORIGIN="${appUrl}"`,
        `WEBAUTHN_RP_NAME="${answers.appName}"`,
        '',
        '# Push Notifications (VAPID)',
        `NEXT_PUBLIC_VAPID_PUBLIC_KEY="${vapidPublic}"`,
        `VAPID_PRIVATE_KEY="${vapidPrivate}"`,
        `VAPID_CONTACT="mailto:${adminEmail}"`,
        '',
        '# Email (Resend)',
        `RESEND_API_KEY="${answers.resendApiKey || ''}"`,
        `EMAIL_FROM="${answers.emailFrom}"`,
        `ADMIN_EMAIL_CC=""`,
        '',
        '# Google Maps (optional)',
        `NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="${answers.googleMapsKey || ''}"`,
        '',
        '# Sentry (optional)',
        `SENTRY_DSN="${answers.sentryDsn || ''}"`,
        `NEXT_PUBLIC_SENTRY_DSN="${answers.sentryDsn || ''}"`,
        '',
        '# Uptime Kuma (optional)',
        `UPTIME_KUMA_URL=""`,
        `UPTIME_KUMA_SLUG=""`,
        '',
        '# GitHub Repository URL (optional, shown in app)',
        `NEXT_PUBLIC_GITHUB_REPO="https://github.com/Zidans-Haare/beer-pong"`,
        '',
        '# Auto-Deploy Webhook (POST /api/deploy)',
        '# Set this as the "Secret" when adding a GitHub webhook to your repo',
        `DEPLOY_SECRET="${deploySecret}"`,
    ];

    fs.writeFileSync(envPath, lines.join('\n') + '\n', 'utf-8');
    return envPath;
}

module.exports = { generateEnv };
